version: "2"

services:
    #  python:
    #    build: ./
    #    volumes:
    #      - ./prototypes:/usr/src/app
    #    depends_on:
    #      - redis
    #      - elasticsearch

  redis:
    image: acefei/redis
    ports:
        - "6379"
    command: redis-server /etc/redis/redis.conf --requirepass acefei

  elasticsearch:
    image: acefei/elasticsearch
    user: "1000"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - ek

  kibana:
    image: acefei/kibana
    volumes:
      - ./kibana/config:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - ek
    depends_on:
      - elasticsearch

networks:
  ek:
    driver: bridge

